version: '3.3'
services:
  chat_api:
    build:
      context: ./api
    container_name: chat_api
    ports:
      - '8443:8443'
      - '3001:3001'

  chat_frontend:
    build:
      context: ./my-app
    container_name: chat_frontend
    ports:
      - '3000:3000'
    links:
      - chat_api
    stdin_open: true

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - '27017:27017'
# Pushing changes
# 1. start the container
# 2. commit changes: docker commit -m "Added LAMP Server" -a "m3lt" pillbar-x-service pillbar/x-service:latest
# 3. push changes: docker push pillbar/x-service

# docker run -it -P27017:27017 -v /var/lib/mongodb:/data/mongo mongo
