version: '3.3'
services:
  chat_db:
    container_name: chat_db
    image: mongo
    ports:
      - '27017:27017'

  chat_api:
    build:
      context: ./api
    container_name: chat_api
    ports:
      - '443:443'
      - '80:80'

    environment:
      PORT: 3001
      PORT_S: 8443 # https
      
    environment:
      # DB
      - MONGODB_DB=ChatApp
      # local (dockerized) db
      - MONGODB_URI=mongodb://chat_db:27017/
      # Atlas db
      # - MONGODB_URI=mongodb+srv://chatapp-user:HKhHFNClKYJvSWDg@cluster0.ucimw.mongodb.net/
      - HOST=0.0.0.0
      # socket.io
      - SOCKET_CORS_HOST=*
    links:
      - chat_db

  chat_frontend:
    build:
      context: ./my-app
    container_name: chat_frontend
    ports:
      - '3000:3000'
    links:
      - chat_api
    stdin_open: true
# docker run -it -P27017:27017 -v /var/lib/mongodb:/data/mongo mongo
